"""Local CJK text rasterization; only small 1-bit labels cross USB, not video."""
from pathlib import Path
from functools import lru_cache
from PIL import Image, ImageDraw, ImageFont
from codex_state import LABELS, Session

WIDTH = 224
# Reserved wire slots keep v1/v2 compatibility; the on-screen queue is removed.
EMPTY_QUEUE = bytes(224*16//8*2)
FONT_CANDIDATES = (
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Medium.ttc",
    "/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf",
)


@lru_cache(maxsize=32)
def font(size):
    for path in FONT_CANDIDATES:
        if Path(path).exists():
            return ImageFont.truetype(path, size)
    raise RuntimeError("No CJK font found: install fonts-noto-cjk or edit FONT_CANDIDATES")


@lru_cache(maxsize=512)
def mask(text, height=24, size=18, align="center"):
    text = str(text).replace("\n", " ")[:80]
    f = font(size)
    while f.getlength(text) > WIDTH - 4 and len(text) > 1:
        text = text[:-2] + "…"
    image = Image.new("L", (WIDTH, height))
    draw = ImageDraw.Draw(image)
    box = draw.textbbox((0, 0), text, font=f)
    x = 2 - box[0] if align == "left" else (WIDTH - (box[2] - box[0])) // 2 - box[0]
    y = (height - (box[3] - box[1])) // 2 - box[1]
    draw.text((x, y), text, font=f, fill=255)
    return image.point(lambda value: 255 if value >= 105 else 0, mode="1").tobytes()


def labels(selected: Session | None, sessions: list[Session], source_error=False, demo=False):
    if selected is None:
        if source_error:
            return mask("状态源异常", align="left")+mask("", align="left")+EMPTY_QUEUE
        return mask("暂无工作对话", align="left")+mask("", align="left")+EMPTY_QUEUE
    position = next(i for i,s in enumerate(sessions) if s.id == selected.id)
    current = f"{selected.short[:12]}  {position + 1}/{len(sessions)}"
    next_short = ""
    if len(sessions) > 1:
        next_short = sessions[(position + 1) % len(sessions)].short[:3] + "…"
    return (mask(current, size=15, align="left") +
            mask(next_short, align="left") +
            EMPTY_QUEUE)


def offline_labels():
    return mask("等待电脑连接", align="left")+mask("", align="left")+EMPTY_QUEUE


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    data = offline_labels()
    lines = ["#pragma once", "#include <stdint.h>", "// Generated by host/text_labels.py from the local Noto/Droid font.",
             "static const uint8_t kOfflineLabels[] = {"]
    lines += ["    " + ",".join(f"0x{x:02X}" for x in data[i:i+24]) + "," for i in range(0,len(data),24)]
    lines.append("};\n")
    args.output.write_text("\n".join(lines))
    print(f"文字生成 [██████████] 100% | 2/2 标签 + 空队列保留位 | {len(data)} bytes", flush=True)
